# Generated by Django 4.1.5 on 2023-01-31 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPlatform',
            fields=[
                ('data_platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='플랫폼 이름')),
                ('des', models.CharField(max_length=1024, verbose_name='플랫폼 설명')),
                ('url', models.CharField(max_length=1024, verbose_name='사이트 주소')),
                ('total_num', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'DataPlatfrom',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512, verbose_name='데이터 이름')),
                ('des', models.CharField(max_length=1024, verbose_name='데이터 설명')),
                ('url', models.CharField(max_length=1024, verbose_name='데이터 주소')),
                ('type', models.CharField(max_length=32, verbose_name='데이터 타입')),
                ('source', models.CharField(max_length=32, verbose_name='source')),
                ('ori_label', models.CharField(max_length=32, verbose_name='ori_label')),
                ('ori_source', models.CharField(max_length=32, verbose_name='ori_source')),
                ('label', models.CharField(max_length=32, verbose_name='label')),
                ('data_platform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.dataplatform')),
            ],
            options={
                'db_table': 'Data',
            },
        ),
    ]
