# Generated by Django 4.1.3 on 2022-11-23 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_user"),
    ]

    operations = [
        migrations.AlterModelTable(name="user", table="User",),
    ]
