# Generated by Django 4.1.3 on 2022-11-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=300, verbose_name="비밀번호"),
        ),
    ]
